name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - run: yarn lint

      - run: yarn build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
